services:  
  api-nest:
    build: 
      context: .
      dockerfile: Dockerfile.local.api
      target: development
    image: resy-takehome-graphql
    command: npm run start
    ports: 
      - 3000:3000
    links: 
      - db:postgres
    depends_on: 
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.local.db
    image: postgres
    # restart: always
    ports: 
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pursuit
      POSTGRES_PASSWORD: pursuit2022